# WunderTools docker-compose
#
####
# Source
#
source:
  image: quay.io/wunder/client-fi-wkfi-source:master
  command:
    - /bin/true
  volumes:
    - "/app/web"
    - "/app/vendor"
    - "/app/config"

####
# Assets
#
assets:
  image: quay.io/wunder/client-fi-wkfi-assets:master
  command:
    - /bin/true
  volumes:
    - "/app/web/sites/default/files"
    - "/app/private"
    - "/app/backup"

####
# DB node
#
db:
    image: quay.io/wunder/client-fi-wkfi-data:master

####
# MemCacheD
#
memcache:
  image: quay.io/wunder/alpine-memcached

####
# FPM node
#

fpm:
  image: quay.io/wunder/wundertools-image-fuzzy-php
  volumes_from:
    - source:ro
    - assets
  links:
    - db:db.app
    - memcache:memcached.app

####
# WWW node
#
www:
  image: quay.io/wunder/wundertools-image-fuzzy-nginx
  volumes_from:
    - source:ro
    - assets:ro
  links:
    - fpm:fpm.app

####
# Static cache service
#
varnish:
  image: quay.io/wunder/alpine-varnish
  environment:
    VARNISH_BACKEND_HOST: backend.app
  links:
    - www:backend.app
