# WunderTools docker-compose
#
version: "2"

services:

  ####
  # Source
  #
  source:
    image: quay.io/wunder/client-fi-wkfi-source:master
    command:
      - /bin/true
    volumes:
      - "/app/web"
      - "/app/vendor"
      - "/app/config"

  ####
  # DB node
  #
  db:
    image: quay.io/wunder/client-fi-wkfi-db:0.2

  ####
  # MemCacheD
  #
  memcache:
    image: quay.io/wunder/alpine-memcached

  ####
  # FPM node
  #

  fpm:
    image: quay.io/wunder/wundertools-image-fuzzy-php
    volumes_from:
      - source:ro
    volumes:
      - "assets/files:/app/web/sites/default/files"
      - "assets/private:/app/private"
      - "backup/archive:/app/backups"
    links:
      - db:db.app
      - memcache:memcached.app

  ####
  # WWW node
  #
  www:
    image: quay.io/wunder/wundertools-image-fuzzy-nginx
    volumes_from:
      - source:ro
    volumes:
      - "assets/files:/app/web/sites/default/files"
      - "assets/private:/app/private"
    links:
      - fpm:fpm.app

  ####
  # Static cache service
  #
  varnish:
    image: quay.io/wunder/alpine-varnish
    environment:
      VARNISH_BACKEND_HOST: backend.app
    links:
      - www:backend.app

volumes:
  db-data:
  assets:
  backups: