# WunderTools docker-compose
#
# REQUIRED VARIABLES:
#
# IMAGE_ROOT : image name root, which has the "-{node}" appended
# IMAGE_VERSION : image tag to be used (master or latest))
# DB_VERSION : image tag for DB, which will change more often
#
# PATH_SOURCE : path on host to folder that contains web & vendor
# PATH_ASSERTS: path on host to folder that contains files, private and backups
# PATH_SETTINGS : path on host to folder that contains drush, console
#
version: "2"

services:

  ####
  # Source
  #
  source:
    image: ${BUILD_IMAGE_ROOT}-source:${IMAGE_VERSION}
    command:
      - /bin/true
    volumes:
      - "${PATH_SOURCE}/web:/app/web"
      - "${PATH_SOURCE}/vendor:/app/vendor"
      - "${PATH_SOURCE}/config:/app/config"

  ####
  # DB node
  #
  db:
    image: ${BUILD_IMAGE_ROOT}-db:${DB_VERSION}
    volumes:
      - "db-data:/var/lib/mysql"

  ####
  # MemCacheD
  #
  memcache:
    image: quay.io/wunder/alpine-memcached

  ####
  # FPM node
  #

  fpm:
    image: quay.io/wunder/wundertools-image-fuzzy-php
    volumes_from:
      - source:ro
    volumes:
      - "${PATH_ASSETS}/files:/app/web/sites/default/files"
      - "${PATH_ASSETS}/private:/app/private"
      - "${PATH_ASSETS}/archive:/app/backups"
    links:
      - db:db.app
      - memcache:memcached.app

  ####
  # WWW node
  #
  www:
    image: quay.io/wunder/wundertools-image-fuzzy-nginx
    volumes_from:
      - source:ro
    volumes:
      - "${PATH_ASSETS}/files:/app/web/sites/default/files"
      - "${PATH_ASSETS}/private:/app/private"
    links:
      - fpm:fpm.app

  ####
  # Static cache service
  #
  varnish:
    image: quay.io/wunder/alpine-varnish
    environment:
      VARNISH_BACKEND_HOST: backend.app
    links:
      - www:backend.app

####
# Define a volume to store database data.
#
volumes:
  db-data: