# WunderTools docker-compose
#
version: "2"

services:

  ####
  # Source
  #
  source:
    image: quay.io/wunder/client-fi-wkfi-source:master
    command:
      - /bin/true
    volumes:
      - "./project/builds/master:/app/web"
      - "./project/settings/drupal:/app/web/sites/default"      
      - "./project/source:/app/web/profiles/wkse"
      - "./project/source/config:/app/config"

  ####
  # Assets
  #
  assets:
    image: quay.io/wunder/client-fi-wkfi-assets:master
    command:
      - /bin/true
    volumes:
      - "./project/assets/files:/app/web/sites/default/files"
      - "./project/assets/private:/app/private"
      - "./project/assets/backups:/app/backups"

  ####
  # DB node
  #
  db:
    image: quay.io/wunder/client-fi-wkfi-db:0.2

  ####
  # MemCacheD
  #
  memcache:
    image: quay.io/wunder/alpine-memcached

  ####
  # FPM node
  #

  fpm:
    image: quay.io/wunder/wundertools-image-fuzzy-php
    volumes_from:
      - source:ro
      - assets
    links:
      - db:db.app
      - memcache:memcached.app

  ####
  # WWW node
  #
  www:
    image: quay.io/wunder/wundertools-image-fuzzy-nginx
    volumes_from:
      - source:ro
      - assets:ro
    links:
      - fpm:fpm.app

  ####
  # Static cache service
  #
  varnish:
    image: quay.io/wunder/alpine-varnish
    environment:
      VARNISH_BACKEND_HOST: backend.app
    links:
      - www:backend.app